### ISSUE TITLE
Link to Basic Usage unavailable

### ISSUE THREAD

**Issue by sushma-4** [sylabs/singularity-cri-userdocs#20]
https://sylabs.io/guides/3.3/user-guide/oci_runtime.html

**Comment by sashayakovtseva** [comment]
Hi @sushma-4 
are you talking about this link?
![image](https://user-images.githubusercontent.com/20927474/60896925-da5b5900-a26f-11e9-9e49-87638204bcdd.png)


It leads to main page of CRI docs, is that the problem?

**Comment by sushma-4** [comment]
This here Sasha  (see, e.g., **Basic Usage** in the Singularity CRI documentation)

**Comment by sashayakovtseva** [comment]
Ok, found it. I think it should go to sylabs/singularity-userdocs

**Comment by sashayakovtseva** [comment]
See sylabs/singularity-userdocs#209
